version: "2"
run:
  tests: true
linters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/shinybell/rpg-market-backend
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
