# rpg-market-backend/.golangci.yml
linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign

linters-settings:
  goimports:
    local-prefixes: github.com/shinybell/rpg-market-backend

run:
  timeout: 5m
  tests: true

issues:
  exclude-use-default: false
